### ISSUE TITLE
Land Area is coming as Blank

### ISSUE THREAD

**Issue by rahulmohan1112** [marinetraffic/mt-ais-toolbox#2]
Hi All,

I had generated the tiff file of the sample dataset attached. I have got the density map but the land/ sea area is not being highlighted. I had tried changing some attributes to the color file as well but was not successful. 

Any help for the same would be highly appreciated. Thanks in advance.

Rahu
![TempGIT](https://user-images.githubusercontent.com/30790334/176880702-048061d8-9622-4080-a81a-b1c99479b09e.png)
l

**Comment by giannismt** [comment]
Dear @rahulmohan1112 ,

Thank you for reaching out and trying this tool. I would say that this behavior is expected. 

What we refer as density maps corresponds to the visualization of total time spent or the unique number of vessels as provided be the configuration parameter "density_method"   (within each cell ). The generated file, is a TIFF geo-referenced file that given a color-scale depicts exactly that. 

You may import the resulting file as a raster layer on most GIS systems (QGIS is a good starting point). 

In such a system, you may add this layer on top of any polygon that contains the coastline (you may use the data/samples/cyclades.json that is also included in this repository) or/and any tile map layer (such as google maps/openstreet maps) to get a representation of the generated maps together with the coastline.

I hope this helps,
Giannis

**Comment by rahulmohan1112** [comment]
Dear Giannis,

I am new to the technical part of GIS environment and the insights shared by you is really appreciated. I will try out to implement the same using QGIS or Openstreet maps software.

Thanks a ton for your response.
Rahul
