### ISSUE TITLE
Windows 10: pygeos wheel build error

### ISSUE THREAD

**Issue by FionaEileen** [marinetraffic/mt-ais-toolbox#3]
Hi,

I am excited to use the mt-ais-toolbox package but am unfortunately falling at the first hurdle. I am using a windows 10 operating system and having issues when installing the packages. 

I have Microsoft Visual C++ 14.3 installed, and opened a virtual environment into which I have downloaded GDAL. However, when I clone the mt-ais-toolbox and subsequently install the packages, the wheel for pygeos fails to build (ERROR: Could not build wheels for pygeos, which is required to install pyproject.toml-based projects). Additionally, it says:  'Could not find geos-config executable. Either append the path to geos-config to PATH or manually provide the include_dirs, library_dirs, libraries and other link args for compiling against a GEOS version >=3.5.'

I have tried researching this error and have found information that the lib and include folders need to be specified manually because there is no geos.config on windows (https://pygeos.readthedocs.io/en/stable/installation.html). However, I do not understand how I can specify the file paths before running the code to install the packages, because the path wouldn't exist yet?

I am new to python so I am quite overwhelmed. If you have any tips or pointers for me, I would hugely appreciate it.

Fiona

**Comment by FionaEileen** [comment]
I had to download GEOS (running and development versions) from OSGeo4w (https://trac.osgeo.org/osgeo4w/), define the paths to the lib and include folders and then I was able to install pygeos successfully. 
https://github.com/pygeos/pygeos/issues/358 
https://pygeos.readthedocs.io/en/latest/installation.html

**Comment by FionaEileen** [comment]
I had to download GEOS (running and development versions) from OSGeo4w (https://trac.osgeo.org/osgeo4w/), define the paths to the lib and include folders and then I was able to install pygeos successfully.
https://github.com/pygeos/pygeos/issues/358
https://pygeos.readthedocs.io/en/latest/installation.html

**Comment by giannismt** [comment]
Hi Fiona,

Apologies for the late response and  thank you for sharing a working solution for your issue.  We will update our documentation as your solution as suggested  workaround for windows OS.

Giannis

**Comment by FionaEileen** [comment]
Hi Giannis,

No worries. I have actually run into another issue. When I try to run the script for merging the sample data, I get an error "ModuleNotFoundError: No module named 'Resource'". When trying to research this error I found information that the resource module is a unix specific package and does not work with a windows OS. Do you know if there is a way to work around this? 

I am considering using a personal laptop, installing ubuntu and running this package there. However, I would prefer to be able to work on this with my university device if possible.

Many thanks,

Fiona

**Comment by giannismt** [comment]
Hi Fiona, 

Thank you for reaching out and using this toolbox even though we do not offer the best support for you OS at the moment.

The fastest way to overcome this issue would be to comment out 3 lines that relate to this package into the ais_merge.py file that are used to max out the available resources and is useful when handling larger dataset. 

So a quick fix is to comment lines 91-94 in ais_merge.py file before installing it.
```
    # import resource

    # soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE)
    # resource.setrlimit(resource.RLIMIT_NOFILE, (hard, hard))`
```
    
  After that you could use python -m pip install -e . and install toolbox from source. 
  Then you should be able to use the package in windows.

Giannis

**Comment by FionaEileen** [comment]
Hi Giannis,

Thank you, that worked for me and I have now been able to successfully run the merging and cleaning steps. I have encountered some additional errors when running the density module: 

'ImportError: Spatial indexes require either `rtree` or `pygeos`. See installation instructions at https://geopandas.org/install.html'.

Since I already have pygeos isntalled, I proceeded to install rtree using: pip install rtree 

This seemed to work fine. I then ran the density script again. When this was finished I had a 'density_time_at_cells_1000_All.csv' in the 03_density, however no density maps were generated and I got the following error:
.
.
'gdal_rasterize' is not recognized as an internal or external command,
operable program or batch file.
'gdaldem' is not recognized as an internal or external command,
operable program or batch file.
.
.
.
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'density_time_at_cells_1000_All.tif'
![Presentation2](https://user-images.githubusercontent.com/97614117/203669994-ed9cc8ed-b1db-4e4d-8689-738d8f935926.png)

**Comment by giannismt** [comment]
Hi Fiona 
looks like your system is not aware of your GDAL installation.  

Could you please verify that the bin directory of your OsGeo installation is included in you PATH environment variable ? ( A reboot might be required to be effective)  

I think that the default installation path is `C:\Windows\OsGeo4W\bin `

Let me know if that works 
Giannis

**Comment by FionaEileen** [comment]
Hi Giannis,

That was indeed the problem, the OSGeo4W\bin directory was not included in my PATH environmental variable. I set it (setx path “%PATH%;C:\OSGeo4W\bin”), rebooted my laptop and when I ran the density code again, it worked! Thank you for your help.

Now I can start working on trying to apply this to the AIS data I am working on!

Many thanks again,

Fiona
