### ISSUE TITLE
Error line 249, in clean_data(TypeError: 'int' object is not iterable)

### ISSUE THREAD

**Issue by FionaEileen** [marinetraffic/mt-ais-toolbox#4]
Hi,

I am applying this package to AIS data that I have acquired for my project. I have created a GeoJSON file of the sea in my study area and put it into the geometry path, and adjusted the configuration file to suit my needs. When I run the data cleaning script I was getting the error: 

  File "C:\...\mt-ais-toolbox\src\mt\cleaning\data_cleaning.py", line 249, in clean_data
    for _polygon in polygons.geoms:
                    ^^^^^^^^^^^^^^
AttributeError: 'Polygon' object has no attribute 'geoms'. Did you mean: '_geom'?

So I changed the code to be 'for _polygon in polygons._geom:'. However, now I am getting the error:

  File "C:\Users\...\mt-ais-toolbox\src\mt\cleaning\data_cleaning.py", line 249, in clean_data
    for _polygon in polygons._geom:
TypeError: 'int' object is not iterable

This makes it seem like the operation assumes it is a multi-polygon object. I thought maybe this was why the polygon_split function was called at the start of the script, so maybe this isn't working as it should? Or perhaps I am completely misinterpreting what the polygon_split is for.

Any insight or help you can give me would be hugely appreciated!

Thanks,

Fiona

**Comment by alextroupi** [comment]
Good afternoon,
Yes the code awaits for a multi-polygon object as you identified already. We're going to update the README file accordingly.
Also, the polygon_split function is used to project each geometry of the multi-polygon object to our grid and speed up the land/sea filtering process.

Alex

**Comment by FionaEileen** [comment]
Hi,

Thank you for this answer, I saved my sea polygon as a multipolygon so that should fix that problem. 

I have another, more general question, about how this package works. Does it only work if the data is split across different csv's by mmsi number? I have several years of data, which I have split by day (as I want to generate daily densities) across different csv's, with data from all vessels from each day in one csv. Can I adapt the the package to process the data in this format, or will I have to split it by day and then by mmsi?

At the moment, I am testing the package on just one day of data, but will I be able to iterate over all the daily csv's to generate daily densities?

Many thanks,

Fiona
