### ISSUE TITLE
ERROR:root:Thread exception (209122000): name 'MMSI' is not defined

### ISSUE THREAD

**Issue by FionaEileen** [marinetraffic/mt-ais-toolbox#8]
When running the data_cleaning.py file I am getting the error: 

ERROR:root:Thread exception (209122000): name 'MMSI' is not defined

for each of the csv files and I don't know how I should try to fix this?

**Comment by giannismt** [comment]
Hi Fiona, 

I  just confirmed that this behavior is related the latest shapely version update.  There have been [some changes in their API ](https://shapely.readthedocs.io/en/stable/migration_pygeos.html#differences-between-pygeos-and-shapely-2-0)in version 2.0.0 that we have not been able to adapt yet. 

You can check the installed version using the `pip freeze` command

A quick test would be fix shapely to version 1.8.5  in your virtual environment
` pip install shapely ==1.8.5`

Let me know if that works

**Comment by FionaEileen** [comment]
Thank you for your response, yes that worked and I was able to successfully run the cleaning and density.py files on my data.
